# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nerve_pb2 as nerve__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nerve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NerveServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/nerve.NerveService/Embed',
                request_serializer=nerve__pb2.EmbedRequest.SerializeToString,
                response_deserializer=nerve__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/nerve.NerveService/EmbedBatch',
                request_serializer=nerve__pb2.BatchEmbedRequest.SerializeToString,
                response_deserializer=nerve__pb2.BatchEmbedResponse.FromString,
                _registered_method=True)
        self.ExtractPDF = channel.unary_unary(
                '/nerve.NerveService/ExtractPDF',
                request_serializer=nerve__pb2.ExtractPDFRequest.SerializeToString,
                response_deserializer=nerve__pb2.ExtractPDFResponse.FromString,
                _registered_method=True)


class NerveServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractPDF(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NerveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=nerve__pb2.EmbedRequest.FromString,
                    response_serializer=nerve__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=nerve__pb2.BatchEmbedRequest.FromString,
                    response_serializer=nerve__pb2.BatchEmbedResponse.SerializeToString,
            ),
            'ExtractPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractPDF,
                    request_deserializer=nerve__pb2.ExtractPDFRequest.FromString,
                    response_serializer=nerve__pb2.ExtractPDFResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nerve.NerveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nerve.NerveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NerveService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nerve.NerveService/Embed',
            nerve__pb2.EmbedRequest.SerializeToString,
            nerve__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nerve.NerveService/EmbedBatch',
            nerve__pb2.BatchEmbedRequest.SerializeToString,
            nerve__pb2.BatchEmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nerve.NerveService/ExtractPDF',
            nerve__pb2.ExtractPDFRequest.SerializeToString,
            nerve__pb2.ExtractPDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
